hlxsites/takeda-ihs

blocks/columns/columns.css
blocks/columns/columns.js
icons/checkmark.svg
icons/fractionation.svg
icons/search-icon.svg
styles/styles.css

Adding the columns for the Plasma-Based Manuafacturing Steps section.
Fix # [Issue 17](https://github.com/hlxsites/takeda-ihs/issues/17)
Existing page: [Manufacturing](https://ihsvirtualexperience.com/manufacturing/)
Test URLs:
- Before: https://main--takeda-ihs--hlxsites.hlx.page/
- After: https://feat-columns--takeda-ihs--hlxsites.hlx.page/drafts/columns

feat: Columns from Issue 17

---

styles/styles.css

#49 
Test URLs:
- After: https://feat-global-styles--takeda-ihs--hlxsites.hlx.page/drafts/style-guide

Intial Global Styling

---

blocks/hero/card-hero.css
blocks/hero/default-hero.css
blocks/hero/hero.css
blocks/hero/product-hero.css

Hero content disappeared with global styles.
Test URLs:
* After: https://bug-hero-content--takeda-ihs--hlxsites.hlx.page/drafts/stopp/hero
* After: https://bug-hero-content--takeda-ihs--hlxsites.hlx.page/drafts/stopp/hero-emphasis
* After: https://bug-hero-content--takeda-ihs--hlxsites.hlx.page/drafts/stopp/hero-product
* After: https://bug-hero-content--takeda-ihs--hlxsites.hlx.page/drafts/stopp/hero-card

Fix hero content layer.

---

blocks/brightcove/brightcove.css
blocks/brightcove/brightcove.js
blocks/footer/footer.css
blocks/footer/footer.js
blocks/header/header.css
styles/reset.css
styles/styles.css

Fix #53 
Test URLs:
- After: https://feat-video-player--takeda-ihs--hlxsites.hlx.page/drafts/stopp/video

Brightcove Player block

---

blocks/quote-banner/quote-banner.css
blocks/quote-banner/quote-banner.js

Fix #5 
Test URLs:
- After: https://feat-quote-banner--takeda-ihs--hlxsites.hlx.page/drafts/stopp/quote-banner

Quote Banner support.

---

blocks/tabs/tabs.css
blocks/tabs/tabs.js
icons/play-pause.svg
styles/styles.css

Fix #4 
Test URLs:
- After: https://feat-tabs--takeda-ihs--hlxsites.hlx.page/drafts/stopp/tabs

Tab Switcher block

---

blocks/cards/cards.css
blocks/cards/cards.js
blocks/cards/cta.css
blocks/cards/cta.js
blocks/cards/icon.css
blocks/cards/icon.js
blocks/cards/product.css
blocks/cards/product.js
blocks/cards/profile.css
blocks/cards/profile.js
styles/styles.css

Fix #13 
Fix #8 
Test URLs:
- After: https://feat-all-cards--takeda-ihs--hlxsites.hlx.page/drafts/stopp/cards

Add all card variations.

---

styles/styles.css

added the full page background gradient from dark to light grey, vertically.  The full gradient is available for any section, and can be coupled with the use of the darkest/lightest colors as the background for adjacent sections.
Fix #7
Test URLs:
- After: https://feat-full-page-gradient--takeda-ihs--hlxsites.hlx.page/drafts/lwintch/page-gradient

feat(full page gradient): adding a full page background gradient

---

scripts/scripts.js
styles/styles.css

Test URLs:
- Before: https://main--takeda-ihs--hlxsites.hlx.page/
- After: https://feat-reference-paragraphs--takeda-ihs--hlxsites.hlx.page/drafts/style-guide

Reference Paragraph support

---

blocks/header/header.css
blocks/hero/default-hero.css
blocks/hero/product-hero.css
blocks/tabs/tabs.js
scripts/scripts.js
styles/styles.css

Test URLs:
- After: https://bug-minor-fixes--takeda-ihs--hlxsites.hlx.page/

Minor Visual Fixes

---

styles/styles.css

Test URLs:
- After: https://cls-perfect-ish-fallback--takeda-ihs--hlxsites.hlx.page/products/

Final Fix for CLS 

---

blocks/fpi-banner/fpi-banner.css
blocks/fpi-banner/fpi-banner.js
blocks/hero/default-hero.css

Fix #32 
Test URLs:
- After: https://feat-fpi-bar--takeda-ihs--hlxsites.hlx.page/products/gammagard-liquid

Add Full Prescribing Information block

---

blocks/floating-images/floating-images.css
blocks/floating-images/floating-images.js
scripts/scripts.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--takeda-ihs--hlxsites.hlx.page/
- After: https://floating-image-revisited--takeda-ihs--hlxsites.hlx.page/drafts/collins/floating-images

Floating image revisited

---

scripts/scripts.js

Fix floating image being applied to every section.
Test URLs:
- After: https://bug-floating-images--takeda-ihs--hlxsites.hlx.page/author-guide/style-guide

Floating Image Bug

---

helix-query.yaml

Fix #86 
Test URLs:
- After: https://feat-query-index--takeda-ihs--hlxsites.hlx.page/

Add index definition.

---

blocks/footer/footer.js
scripts/scripts.js
styles/styles.css

Fix #87 
Test URLs:
- After: https://styles-backgrounds--takeda-ihs--hlxsites.hlx.page/author-guide/style-guide

Background Style Names

---

README.md
blocks/cards/product.css
blocks/footer/footer.css
blocks/hero/product-hero.css
blocks/isi-tray/isi-tray.css
styles/styles.css

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--takeda-ihs--hlxsites.hlx.page/
- After: https://product-page-defects--takeda-ihs--hlxsites.hlx.page/

Product page defects

---

blocks/cards/product.css
blocks/hero/default-hero.css
scripts/scripts.js
styles/styles.css

Test URLs:
- After: https://bug-inline-image--takeda-ihs--hlxsites.hlx.page/programs/population-health

Support proper height inline-images.

---

blocks/section-background-image-gradient/section-background-image-gradient.css
scripts/scripts.js
styles/styles.css

Fix #14 
Test URLs:
- After: https://feat-gradient-background-image--takeda-ihs--hlxsites.hlx.page/drafts/stopp/gradient-background-test

Gradient Background terminating in an Image

---

blocks/cards/cards.css
blocks/cards/cards.js
blocks/cards/icon-cta.css
blocks/cards/icon-cta.js
blocks/cards/icon.css
blocks/cards/icon.js
blocks/columns/columns.css
blocks/columns/columns.js
scripts/scripts.js
styles/styles.css

Fix #100 
Test URLs:
- After: https://bug-columns--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/columns
- After: https://bug-columns--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/cards
- After: https://bug-columns--takeda-ihs--hlxsites.hlx.page/drafts/stopp/manufacturing

Add new card variation and better support columns.

---

blocks/hero/hero.js

Test URLs:
- After: https://bug-hero--takeda-ihs--hlxsites.hlx.page/

Fix Missing Heros

---

scripts/scripts.js

Test URLs:
- After: https://bug-section-bg-error--takeda-ihs--hlxsites.hlx.page/programs/population-health

Fix error for non-bg section pages.

---

blocks/hero/hero.js
styles/styles.css

Fix #109
Test URLs:
- After: https://bug-more-hero-issues--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/hero/default
- After: https://bug-more-hero-issues--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/hero/style-variations
- After: https://bug-more-hero-issues--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/hero/card
- After: https://bug-more-hero-issues--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/product

Fix Hero image bugs.

---

blocks/hero/hero.css

Test URLs:
- After: https://feat-quartz-hero--takeda-ihs--hlxsites.hlx.page/

Add Quartz background option.

---

blocks/quote-banner/quote-banner.css

Fix #124 
Test URLs:
- After: https://bug-quote-banner--takeda-ihs--hlxsites.hlx.page/

Dont limit size on quote banner

---

blocks/hero/hero.css
styles/styles.css

Fix #116 
Fix #119 
Test URLs:
- After: https://bug-stewardship--takeda-ihs--hlxsites.hlx.page/programs/stewardship-series?lighthouse=on

Fix Styles on stewardship page.

---

scripts/scripts.js
styles/styles.css

Fix #114 
Test URLs:
- After: https://feat-boxshadow-image--takeda-ihs--hlxsites.hlx.page/manufacturing/

Fix image and ref styles.

---

blocks/cards/icon-cta.css
blocks/cards/icon-cta.js

Test URLs:
- After: https://bug-card-icon-cta--takeda-ihs--hlxsites.hlx.page/?lighthouse=on

Fix cards to have full link and hover state.

---

scripts/delayed.js
scripts/scripts.js

Fix #117 
Test URLs:
- After: https://feat-onetrust-cookie--takeda-ihs--hlxsites.hlx.page/?lighthouse=on

Add OneTrust call.

---

scripts/delayed.js
scripts/scripts.js

Reverts hlxsites/takeda-ihs#125
This PR was left open whlie confirming OneTrust and GTM were cooperating appropriately.

Revert "Add OneTrust call."

---

blocks/grid/grid.css
blocks/grid/grid.js
icons/check-circle.svg
scripts/scripts.js
scripts/third-party.js
styles/styles.css

adding support for a grid on the services page with a background gradient section and including the clip-path on the hero when the section has an inverted gradient background.
Fix #133
Test URLs:
- Before: https://main--takeda-ihs--hlxsites.hlx.page/service?lighthouse=on
- After: https://fix-133-gradient-bg--takeda-ihs--hlxsites.hlx.page/drafts/lwintch/service?lighthouse=on

feat(grid block): adding a grid component
